name: Move Old Google Sheet Rows

on:
  schedule:
    - cron: '0 5 * * *'  # every day at 05:00 UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  move-old-rows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write Google credentials
        run: echo "${{ secrets.GOOGLE_CREDS_JSON }}" > service-account-creds.json

      - name: Set environment variables
        run: |
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CREDS=service-account-creds.json" >> $GITHUB_ENV

      - name: Run script
        run: python move_old_changes.py
