name: Move Old Google Sheet Rows

on:
  schedule:
    - cron: '0 5 * * *'  # every day at 05:00 UTC
  workflow_dispatch:     # allows manual trigger

jobs:
  move-old-rows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread google-auth python-dotenv

      - name: Write Google credentials to file
        run: |
          echo "SERVICE_ACCOUNT_JSON" > service-account-creds.json
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}

      - name: Print first line of credentials (debug only)
        run: head -n 5 service-account-creds.json

      - name: Set environment variables
        run: |
          echo "SPREADSHEET_ID=${{ secrets.SPREADSHEET_ID }}" >> $GITHUB_ENV
          echo "SERVICE_ACCOUNT_JSON=service-account-creds.json" >> $GITHUB_ENV

      - name: Run the script
        run: python move_old_changes.py